bands = [
    ('10cc', '10cc'),
    ('4 non blondes', '4 Non Blondes'),
    ('ac/dc', 'AC_DC'),
    ('ac_dc', 'AC_DC'),
    ('aerosmith', 'Aerosmith'),
    ('alan parsons project', 'The Alan Parsons Project'),
    ('alanis morissette', 'Alanis Morissette'),
    ('alphaville', 'Alphaville'),
    ('animals', 'The Animals'),
    ('april wine', 'April Wine'),
    ('arctic monkeys', 'Arctic Monkeys'),
    ('b.b king', 'B.B. King'),
    ('b.b. king', 'B.B. King'),
    ('bad company', 'Bad Company'),
    ('bb king', 'B.B. King'),
    ('beatles', 'The Beatles'),
    ('beck', 'Beck'),
    ('billy joel', 'Billy Joel'),
    ('black sabbath', 'Black Sabbath'),
    ('blondie', 'Blondie'),
    ('bo diddley', 'Bo Diddley'),
    ('bob dylan', 'Bob Dylan'),
    ('bob marley', 'Bob Marley'),
    ('boston', 'Boston'),
    ('bruce springsteen', 'Bruce Springsteen'),
    ('buddy holly', 'Buddy Holly'),
    ('cake', 'CAKE'),
    ('carlos santana', 'Carlos Santana'),
    ('cars', 'The Cars'),
    ('ccr', 'Creedence Clearwater Revival'),
    ('cher', 'Cher'),
    ('chicago', 'Chicago'),
    ('chuck berry', 'Chuck Berry'),
    ('clash', 'The Clash'),
    ('coldplay', 'Coldplay'),
    ('cream', 'Cream'),
    ('creedence clearwater revival', 'Creedence Clearwater Revival'),
    ('cure', 'The Cure'),
    ('david bowie', 'David Bowie'),
    ('dead kennedys', 'Dead Kennedys'),
    ('deep purple', 'Deep Purple'),
    ('def leppard', 'Def Leppard'),
    ('dio', 'Dio'),
    ('dire straits', 'Dire Straits'),
    ('don mclean', 'Don McLean'),
    ('doors', 'The Doors'),
    ('duran duran', 'Duran Duran'),
    ('eagles', 'The Eagles'),
    ('electric light orchestra', 'Electric Light Orchestra'),
    ('electric wizard', 'Electric Wizard'),
    ('elo', 'Electric Light Orchestra'),
    ('elvis presley', 'Elvis Presley'),
    ('elvis', 'Elvis Presley'),
    ('eric clapton', 'Eric Clapton'),
    ('essex green', 'The Essex Green'),
    ('europe', 'Europe'),
    ('fats domino', 'Fats Domino'),
    ('fleetwood mac', 'Fleetwood Mac'),
    ('foo fighters', 'Foo Fighters'),
    ('foreigner', 'Foreigner'),
    ('frank sinatra', 'Frank Sinatra'),
    ('frank zappa', 'Frank Zappa'),
    ('free', 'Free'),
    ('gary moore', 'Gary Moore'),
    ('george harrison', 'George Harrison'),
    ('gotye', 'Gotye'),
    ('greg lake', 'Greg Lake'),
    ('heart', 'Heart'),
    ('iggy and the stooges', 'The Stooges'),
    ('iggy pop', 'Iggy Pop'),
    ('inxs', 'INXS'),
    ('iron maiden', 'Iron Maiden'),
    ('j.j cale', 'J.J. Cale'),
    ('j.j. cale', 'J.J. Cale'),
    ('james blunt', 'James Blunt'),
    ('jane\'s addiction', 'Jane\'s Addiction'),
    ('janis joplin', 'Janis Joplin'),
    ('jefferson airplane', 'Jefferson Airplane'),
    ('jet', 'Jet'),
    ('jimi hendrix experience', 'Jimi Hendrix'),
    ('jimi hendrix', 'Jimi Hendrix'),
    ('jimmy cliff', 'Jimmy Cliff'),
    ('jj cale', 'J.J. Cale'),
    ('joe cocker', 'Joe Cocker'),
    ('john lennon', 'John Lennon'),
    ('joy division', 'Joy Division'),
    ('kansas', 'Kansas'),
    ('kate bush', 'Kate Bush'),
    ('kings of leon', 'Kings Of Leon'),
    ('kinks', 'The Kinks'),
    ('knack', 'The Knack'),
    ('kyuss', 'Kyuss'),
    ('led zeppelin', 'Led Zeppelin'),
    ('locomondo', 'Locomondo'),
    ('lou reed', 'Lou Reed'),
    ('louis armstrong', 'Louis Armstrong'),
    ('lynard skynard', 'Lynard Skynard'),
    ('marillion', 'Marillion'),
    ('marilyn manson', 'Marilyn Manson'),
    ('mars red sky', 'Mars Red Sky'),
    ('meat puppets', 'Meat Puppets'),
    ('morrissey', 'Morrissey'),
    ('muddy waters', 'Muddy Waters'),
    ('mungo jerry', 'Mungo Jerry'),
    ('neil young', 'Neil Young'),
    ('neutral milk hotel', 'Neutral Milk Hotel'),
    ('new york dolls', 'New York Dolls'),
    ('nine inch nails', 'Nine Inch Nails'),
    ('nirvana', 'Nirvana'),
    ('outfields', 'The Outfields'),
    ('patti smith', 'Patti Smith'),
    ('paul mccartney', 'Paul McCartney'),
    ('pearl jam', 'Pearl Jam'),
    ('phil collins', 'Phil Collins'),
    ('pink floyd', 'Pink Floyd'),
    ('pixies', 'Pixies'),
    ('placebo', 'Placebo'),
    ('police', 'The Police'),
    ('prince', 'Prince'),
    ('queen', 'Queen'),
    ('question mark & the mysterians', 'Question Mark & the Mysterians'),
    ('question mark and the mysterians', 'Question Mark & the Mysterians'),
    ('r.e.m.', 'REM'),
    ('rage against the machine', 'Rage Against The Machine'),
    ('rainbow','Rainbow'),
    ('ramones', 'The Ramones'),
    ('rare earth', 'Rare Earth'),
    ('ratm', 'Rage Against The Machine'),
    ('red hot chili peppers', 'Red Hot Chili Peppers'),
    ('rem', 'REM'),
    ('reo speedwagon', 'REO Speedwagon'),
    ('rhcp', 'Red Hot Chili Peppers'),
    ('ringo star', 'Ringo Star'),
    ('ringo', 'Ringo Star'),
    ('robert plant', 'Robert Plant'),
    ('rod steward', 'Rod Steward'),
    ('rolling stones', 'The Rolling Stones'),
    ('romantics', 'The Romantics'),
    ('roxette', 'Roxette'),
    ('roxy music', 'Roxy Music'),
    ('semisonic', 'Semisonic'),
    ('sex pistols', 'The Sex Pistols'),
    ('simple minds', 'Simple Minds'),
    ('slipknot', 'Slipknot'),
    ('smashing pumpkins', 'The Smashing Pumpkins'),
    ('smiths', 'The Smiths'),
    ('soad', 'System Of A Down'),
    ('socrates', 'Socrates Drank The Conium'),
    ('socrates drank the conium', 'Socrates Drank The Conium'),
    ('sonic youth', 'Sonic Youth'),
    ('sonics', 'Sonics'),
    ('soundgarden', 'Soundgarden'),
    ('spin doctors', 'Spin Doctors'),
    ('steve miller band', 'Steve Miller Band'),
    ('stevie wonder', 'Stevie Wonder'),
    ('stone roses', 'The Stone Roses'),
    ('stone temple pilots', 'Stone Temple Pilots'),
    ('stooges', 'The Stooges'),
    ('sun ra', 'Sun Ra'),
    ('sweet', 'Sweet'),
    ('system of a down', 'System Of A Down'),
    ('system of the down', 'System Of A Down'),
    ('talking heads', 'Talking Heads'),
    ('television', 'Television'),
    ('tesla', 'Tesla'),
    ('the band', 'The Band'),
    ('thin lizzy', 'Thin Lizzy'),
    ('traffic', 'Traffic'),
    ('u2', 'U2'),
    ('velvet underground', 'The Velvet Underground'),
    ('waterboys', 'The Waterboys'),
    ('weezer', 'Weezer'),
    ('what the funk', 'What The Funk'),
    ('white stripes', 'The White Stripes'),
    ('who', 'The Who'),
    ('yardbirds', 'The Yardbirds'),
    ]
